import Foundation

enum ConfigWriter {

    static var shimConfigURL: URL {
        FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent(".codex-shim/config.toml")
    }

    static func write(
        models: [ShimModel],
        catalogPath: String,
        port: Int,
        to url: URL = shimConfigURL
    ) throws -> URL {
        let fm = FileManager.default
        try fm.createDirectory(at: url.deletingLastPathComponent(), withIntermediateDirectories: true)

        let usable = models.filter { !$0.apiKey.isEmpty }
        let defaultSlug: String
        if let first = usable.first {
            defaultSlug = first.slug
        } else if let first = models.first {
            defaultSlug = first.slug
        } else {
            defaultSlug = "codex-shim-default"
        }

        let text = """
        # Generated by codex-shim. This file is opt-in and is not ~/.codex/config.toml.
        model = "\(TOMLEscaper.escape(defaultSlug))"
        model_provider = "\(CatalogWriter.providerName)"
        model_catalog_json = "\(TOMLEscaper.escape(catalogPath))"

        [model_providers.\(CatalogWriter.providerName)]
        name = "Codex Shim"
        base_url = "http://127.0.0.1:\(port)/v1"
        wire_api = "responses"
        experimental_bearer_token = "dummy"
        request_max_retries = 3
        stream_max_retries = 3
        stream_idle_timeout_ms = 600000
        """

        try text.data(using: .utf8)?.write(to: url, options: .atomic)
        return url
    }
}
