import XCTest
@testable import Shimbar

final class ConfigWriterTests: XCTestCase {

    private var tempDir: URL!

    override func setUp() {
        super.setUp()
        tempDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("config-writer-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: tempDir)
        super.tearDown()
    }

    private func makeModel(slug: String, apiKey: String = "sk-test") -> ShimModel {
        ShimModel(
            slug: slug,
            model: slug,
            displayName: slug.replacingOccurrences(of: "-", with: " ").capitalized,
            provider: "openai",
            baseUrl: "https://api.example.com/v1",
            apiKey: apiKey
        )
    }

    // MARK: - Round-Trip Template

    func testWriteProducesValidTOML() throws {
        let models = [makeModel(slug: "claude-sonnet-4")]
        let configURL = tempDir.appendingPathComponent("config.toml")

        try ConfigWriter.write(
            models: models,
            catalogPath: "/home/user/.codex-shim/custom_model_catalog.json",
            port: 8765,
            to: configURL
        )

        let text = try String(contentsOf: configURL, encoding: .utf8)

        XCTAssertTrue(text.hasPrefix("# Generated by codex-shim"))
        XCTAssertTrue(text.contains("model = \"claude-sonnet-4\""))
        XCTAssertTrue(text.contains("model_provider = \"codex_shim\""))
        XCTAssertTrue(text.contains("model_catalog_json = \"/home/user/.codex-shim/custom_model_catalog.json\""))
        XCTAssertTrue(text.contains("[model_providers.codex_shim]"))
        XCTAssertTrue(text.contains("base_url = \"http://127.0.0.1:8765/v1\""))
        XCTAssertTrue(text.contains("wire_api = \"responses\""))
        XCTAssertTrue(text.contains("stream_idle_timeout_ms = 600000"))
    }

    func testWriteUsesFirstUsableModel() throws {
        let models = [
            makeModel(slug: "model-a", apiKey: ""),
            makeModel(slug: "model-b", apiKey: "sk-live"),
            makeModel(slug: "model-c", apiKey: "sk-other")
        ]
        let configURL = tempDir.appendingPathComponent("config.toml")

        try ConfigWriter.write(
            models: models,
            catalogPath: "/path/catalog.json",
            port: 9000,
            to: configURL
        )

        let text = try String(contentsOf: configURL, encoding: .utf8)
        XCTAssertTrue(text.contains("model = \"model-b\""))
        XCTAssertTrue(text.contains("http://127.0.0.1:9000/v1"))
    }

    func testWriteEscapesSpecialCharacters() throws {
        let models = [makeModel(slug: "model-with-backslash\\slash")]
        let configURL = tempDir.appendingPathComponent("config.toml")

        try ConfigWriter.write(
            models: models,
            catalogPath: "/path/with \"quotes\"/catalog.json",
            port: 8765,
            to: configURL
        )

        let text = try String(contentsOf: configURL, encoding: .utf8)
        XCTAssertTrue(text.contains("model-with-backslash\\\\slash"))
        XCTAssertTrue(text.contains("/path/with \\\"quotes\\\"/catalog.json"))
    }

    func testWriteCreatesParentDirectory() throws {
        let nested = tempDir.appendingPathComponent("a/b/c/config.toml")
        let models = [makeModel(slug: "test-model")]

        try ConfigWriter.write(
            models: models,
            catalogPath: "/catalog.json",
            port: 8765,
            to: nested
        )

        XCTAssertTrue(FileManager.default.fileExists(atPath: nested.path))
    }
}
